name: Deploy to cPanel

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Déclaration des variables d'environnement
    env:
      DEV_REMOTE_DIR: dev.ecole-st-augustin.fr/v2/app
      PROD_REMOTE_DIR: prod.ecole-st-augustin.fr/v2/app

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.16.0'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # Définir le répertoire distant en fonction de la branche
      - name: Set remote directory
        id: set-dir
        run: |
          if [ $GITHUB_REF == 'refs/heads/main' ]; then
            echo "REMOTE_DIR=${{ env.PROD_REMOTE_DIR }}" >> $GITHUB_ENV
          else
            echo "REMOTE_DIR=${{ env.DEV_REMOTE_DIR }}" >> $GITHUB_ENV
          fi

      - name: Decode FTP password
        id: decode-password
        run: echo "${{ secrets.DEV_CPANEL_FTP_PASSWORD_BASE64 }}" | base64 --decode | tr -d '\n' > ftp_password.txt

      - name: Set FTP password environment variable
        run: echo "FTP_PASSWORD=$(cat ftp_password.txt)" >> $GITHUB_ENV

      - name: Upload to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.DEV_CPANEL_FTP_HOST }}
          username: ${{ secrets.DEV_CPANEL_FTP_USERNAME }}
          password: ${{ env.FTP_PASSWORD }} # Utilisation de la variable d'environnement pour le mot de passe
          local-dir: ./.next/
          remote-dir: ${{ env.REMOTE_DIR }} # Utilisation du chemin distant
