name: Deploy to cPanel

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Set remote directory
        id: set-dir
        run: echo "REMOTE_DIR=/home/bdeh8989/public_html/$(if [ $GITHUB_REF == 'refs/heads/main' ]; then echo 'ecole-st-augustin-v2-prod'; else echo 'ecole-st-augustin-v2-dev'; fi)" >> $GITHUB_ENV

      - name: Upload to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          host: ${{ secrets.CPANEL_FTP_HOST }}
          username: ${{ secrets.CPANEL_FTP_USERNAME }}
          password: ${{ secrets.CPANEL_FTP_PASSWORD }}
          local-dir: ./dist
          remote-dir: ${{ env.REMOTE_DIR }}
