name: Build

on:
  push:
    branches:
      - dev # Ce workflow se déclenche lors des pushs sur la branche 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configuration de Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.16.0' # Utilisez la version de Node.js que vous souhaitez

      # Étape 3 : Installation des dépendances
      - name: Install dependencies
        run: npm install

      # Étape 4 : Build du projet
      - name: Build the project
        run: npm run build # Assurez-vous que cette commande existe dans votre package.json
